### PR TITLE
initial push

### PR DESCRIPTION
**Pull request by jmarcusgill**

### CODE REVIEW

**Comment by jmarcusgill** [comment]
Got everything pretty much working. Need to figure out how to put my cards into rows...

**Comment by jmarcusgill** [comment]
I believe the assignment is met, hopefully!

**Comment by zoeames** [comment]
@jmarcusgill A great start but a couple things need to get fixed.  
1.  your readme needs some work - take out the instructions they are in their own md file. The readme should have description, screenshot(s), and instructions for how to run.  
2.  when i click on a card the background color should change.  
3.  If i click on a card and type and then click on a second card the stuff i typed in the input for the first card is still there.
4. Add some more cars to your json file.  When there are more than 3 cars there should be 2 different rows.  currently one row is nested in the other.

**Comment by jmarcusgill** [comment]
@zoeames, 
I think I adjusted the issues you pointed out. Feel free to take a look at my code to see if I met the challenge aside from issue 1. I should have some time after class to work on my README, planning on having this thing approved and merged before class begins tomorrow!

**Comment by zoeames** [comment]
@jmarcusgill looks good.  I am just waiting on the readme to approve

**Comment by jmarcusgill** [comment]
@zoeames, README added with pic. Think it's ready to be merged.

**Comment by zoeames** [comment]
looks good 👍

**Pull request merged**
